#!/bin/bash

if [[ "$(whoami)" == "root" ]];then
  if [[ $1 == "start" ]];then
    kalivnc startservice
  elif [[ $1 == "stop" ]] && [ -z "$2" ];then
    kalivnc stopservice
  else
    echo "usage : confservice [start|stop]"
  fi
else
  echo "! get root access"
fi
